#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 22 15:21:28 CEST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Xonks-Bliss-Wildeprojekt-Settings.zip
enableShaders=false
