#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 14 21:06:43 CEST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
