#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 01 19:43:42 CEST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Xonks-Bliss-ArdaCraft-Settings
enableShaders=false
